# Generated by Django 4.2.26 on 2025-12-13 04:11

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='salesperson',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='primary_salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to='accounts.salesperson'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='UserProxy',
        ),
        migrations.AddField(
            model_name='customermembership',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='customermembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='customermembership',
            unique_together={('user', 'customer')},
        ),
    ]
