# Generated by Django 4.2.26 on 2025-11-14 03:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('vessel_use', models.CharField(blank=True, max_length=64, null=True)),
                ('duty_cycle', models.CharField(blank=True, max_length=64, null=True)),
                ('propulsion_type', models.CharField(blank=True, max_length=64, null=True)),
                ('hybrid_or_brake', models.BooleanField(null=True)),
                ('transmission_config', models.CharField(blank=True, max_length=64, null=True)),
                ('engine_manufacturer', models.CharField(blank=True, max_length=64, null=True)),
                ('measurement_units', models.CharField(blank=True, max_length=64, null=True)),
                ('engine_power', models.FloatField(blank=True, null=True)),
                ('engine_rated_rpm', models.IntegerField(blank=True, null=True)),
                ('selected_series', models.CharField(blank=True, max_length=128, null=True)),
                ('selected_model', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
