# Generated by Django 4.2.26 on 2025-11-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productconfiguration',
            old_name='measurement_units',
            new_name='ratio',
        ),
        migrations.RemoveField(
            model_name='productconfiguration',
            name='engine_rated_rpm',
        ),
        migrations.AddField(
            model_name='productconfiguration',
            name='power_factor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
