# Generated by Django 4.2.26 on 2025-11-14 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_rename_measurement_units_productconfiguration_ratio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productconfiguration',
            name='engine_power',
        ),
    ]
