# Generated by Django 4.2.26 on 2025-11-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0003_remove_productconfiguration_engine_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='productconfiguration',
            name='selected_model_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
