# Generated by Django 4.2.26 on 2025-11-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0004_productconfiguration_selected_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productconfiguration',
            name='actuation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productconfiguration',
            name='bellhousing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productconfiguration',
            name='inputflange',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productconfiguration',
            name='monitoring',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productconfiguration',
            name='mountings',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productconfiguration',
            name='propflange',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productconfiguration',
            name='ptishaftbrake',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productconfiguration',
            name='pto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productconfiguration',
            name='trailingpump',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productconfiguration',
            name='trolling',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
