# Generated by Django 4.2.26 on 2025-11-14 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('marine', 'Marine'), ('industrial', 'Industrial')], max_length=20)),
                ('duty_cycle', models.CharField(blank=True, max_length=50)),
                ('propulsion', models.CharField(blank=True, max_length=50)),
                ('transmission_config', models.CharField(blank=True, max_length=50)),
                ('engine_manufacturer', models.CharField(blank=True, max_length=50)),
                ('unit_system', models.CharField(default='imperial', max_length=20)),
                ('power_value', models.FloatField(blank=True, null=True)),
                ('rpm_value', models.IntegerField(blank=True, null=True)),
                ('primary_use', models.CharField(blank=True, max_length=50)),
                ('hybrid', models.CharField(blank=True, max_length=10)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
