# Generated by Django 4.2.26 on 2025-11-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='description',
        ),
        migrations.AddField(
            model_name='part',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
