# Generated by Django 4.2.26 on 2025-12-12 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_remove_family_description_part_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration', models.PositiveIntegerField(default=1)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('transaction_type', models.CharField(blank=True, choices=[('Inbox', 'Inbox'), ('Outbox', 'Outbox')], max_length=10, null=True)),
                ('transaction_status', models.CharField(blank=True, choices=[('New', 'New'), ('Received', 'Received'), ('Read', 'Read')], max_length=10, null=True)),
                ('request_type', models.CharField(blank=True, max_length=50, null=True)),
                ('email_body', models.TextField(blank=True, null=True)),
                ('json_file', models.JSONField(blank=True, null=True)),
                ('pdf_path', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.customer')),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.salesperson')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
                'indexes': [models.Index(fields=['iteration'], name='transaction_iterati_d2d997_idx')],
            },
        ),
    ]
